prompts = [
    ("Erstelle eine Webseite mit einer Überschrift, einem Absatz und einer Schaltfläche.", "Einfach"),
    ("Erstelle ein Kontaktformular mit Feldern für Name, E-Mail und Nachricht.", "Einfach"),
    ("Verwende eine serifenlose Schriftart für die gesamte Seite und stelle sicher, dass die Überschriften fett sind.", "Einfach"),
    ("Füge einer Webseite eine Hover-Animation für Schaltflächen hinzu, bei der die Hintergrundfarbe langsam wechselt.", "Einfach"),
    ("Erstelle eine Schaltfläche, die bei Klick ihre Farbe ändert.", "Einfach"),
    ("Erstelle eine Hero-Section mit einem großen Bild, einem Titel und einem Call-to-Action-Button.", "Einfach"),
    ("Erstelle eine Webseite mit einer dreispaltigen Grid-Anordnung, einer Navigationsleiste und einer Fußzeile.", "Mittel"),
    ("Erstelle ein responsives Layout mit einem Header, einer Sidebar und einem Hauptinhalt.", "Mittel"),
    ("Erstelle eine React-Komponente für ein Login-Formular.", "Mittel"),
    ("Erstelle eine Tab-Navigationsleiste mit drei Tabs: ‚Übersicht‘, ‚Details‘ und ‚Einstellungen‘.", "Mittel"),
    ("Erstelle eine Komponente für ein Bilderkarussell mit Vorwärts- und Rückwärts-Schaltflächen.", "Mittel"),
    ("Erstelle eine Blog-Seite mit einem Header, einer Liste von Blog-Beiträgen und einer Suchfunktion.", "Mittel"),
    ("Erstelle eine Landing Page für ein fiktives Produkt, einschließlich einer Beschreibung, einer Bildergalerie und einer Schaltfläche zum Kaufen.", "Mittel"),
    ("Erstelle eine vollständige Webseite mit einem Hauptmenü, einer Produktliste im Grid-Format und einem Kontaktformular.", "Komplex"),
    ("Erstelle ein Dashboard mit einem Kreisdiagramm, einem Balkendiagramm und einem Bereich für Statistiken.", "Komplex"),
    ("Erstelle eine Portfolio-Webseite mit einer Liste von Projekten und einem Kontaktformular.", "Komplex"),
    ("Erstelle eine SEO-freundliche HTML-Seite mit Meta-Tags für Titel, Beschreibung und Keywords.", "Komplex"),
    ("Erstelle eine barrierefreie Webseite mit ARIA-Labels für alle interaktiven Elemente.", "Komplex"),
    ("Erstelle ein mehrstufiges Formular mit einer Fortschrittsanzeige, das nacheinander persönliche Daten, Adresse und Zahlungsinformationen abfragt.", "Komplex"),
    ("Erstelle eine E-Commerce-Seite mit einer Produktseite, einer Bildergalerie, einer Preisangabe und einer Schaltfläche ‚In den Warenkorb‘.", "Komplex"),
]
